version: '3'
services:
  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - my-network

  selenium-node-chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - my-network

  python-script:
    build:
      context: .
    depends_on:
      - selenium-hub
    environment:
      - GRID_URL=http://selenium-hub:4444/wd/hub
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
